# Generated by Django 5.1.7 on 2025-03-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_signupdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Todolist',
        ),
    ]
